"""Parámetros para la simulación gráfica de una cola de cajero."""

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 650
SERVER_CAPACITY = 5
AUTOMATIC_RESPOND_TIME = 200
MAX_PRIORITY = 5
MAX_AGE = 20
RANDOM_ADD_PROB = 0.05

TEXTBOX_PADDING = 5
GRANT_PADDING = 5
GRANT_TIME_WIDTH = 20
