"""Parámetros para la simulación gráfica de una cola de cajero."""

SCREEN_WIDTH = 900
SCREEN_HEIGHT = 650
SERVER_CAPACITY = 0
AUTOMATIC_RESPOND_TIME = 200
ENABLE_PRIORITY = False

TEXTBOX_PADDING = 5
GRANT_PADDING = 5
GRANT_TIME_WIDTH = 20
